server:
  port: 8081

Scheduled:
  monthRate: '0/5 * * * * ?'
  dayRate: '0/2 * * * * ?'

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/threesome?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
