server:
  port: 8082

spring:
  application:
    name: FileETLSrv
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采用比例，默认 0.1 全部采样 1.0
  zipkin:
    base-url: http://localhost:9411